---
title: Tocaya Organica
timezone: UTC
collections:
  locations:
    title: Locations
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
navigation-logo: "/uploads/logo-rectangle.png"
footer-logo: "/uploads/logo-rectangle-light.png"
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: 
markdown: kramdown
plugins:
- jekyll-feed
