---
title: Tocaya Organica
timezone: UTC
collections:
  locations:
    title: Locations
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: locations
  values:
    is-open: false
    address:
      street: 
      city: 
      zip: 
    phone-number: 
    hours: []
    special-hours: []
    postmates-link: 
    uber-eats-link: 
navigation-logo: "/uploads/logo-rectangle.png"
footer-logo: "/uploads/logo-rectangle-light.png"
instagram-link: https://www.instagram.com/tocayaorganica/
facebook-link: https://www.facebook.com/TocayaOrganica/
twitter-link: https://twitter.com/tocayaorganica/
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: 
markdown: kramdown
plugins:
- jekyll-feed
test: test2
